### ISSUE TITLE
Default scraper "didn't return a streamable url"

### ISSUE THREAD

**Issue by yoshinoa** [JDALab/film-central#20]
When attempting to stream something with the default scraper I get this error:

```
mov-cli -s films.default house

Good Afternoon, xxxxx.
    It's 02:12 PM on a gorgeous Tuesday!

[INFO] (mov_cli) - Using 'films.default' scraper...
[INFO] (mov_cli) - Searching for 'house'...
[INFO] (mov_cli) - Scrapping episodes for 'House'...
[INFO] (mov_cli) - Scrapping media for 'House'...
[ERROR] (mov_cli) - Scraper didn't return a streamable url.
This is NOT a mov-cli issue. This IS an plugin issue
```

**Comment by THEGOLDENPRO** [comment]
I can't reproduce this exactly but I did have trouble streaming that and it seems to be a provider issue so we can't fix this. 

@r3tr0ananas also what's the reasoning behind returning the url as None?

**Comment by GnotAI** [comment]
> I can't reproduce this exactly but I did have trouble streaming that and it seems to be a provider issue so we can't fix this.
> 
> @r3tr0ananas also what's the reasoning behind returning the url as None?

If this is a provider issue, then why is it still an open problem?
